[package]
name = "axum-fields-example"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-multer = { path = "../..", features = ["axum"] }
axum = "0.7"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
