name: CI

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Cargo Check
        run: cargo check --all-targets --all-features

      - name: Cargo Test
        run: cargo test --all-features

      - name: Cargo Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Cargo Docs
        run: cargo doc --all-features --no-deps

      - name: Check Examples
        run: cargo check --examples --all-features

  msrv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust 1.88.0
        uses: dtolnay/rust-toolchain@1.88.0

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Cargo Check (MSRV)
        run: cargo +1.88.0 check --all-targets --all-features
